#page title
#page_title                                : "Find: Command+F for Camera"                                         # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.


baseurl                                   : /Find-app

# App Info
ios_app_id                                : 1506500202                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    : https://emilbaehr.com                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appIcon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : "Find: Command+F for Camera"                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Free • no ads or in-app purchases
app_description                           : Find text in real life - fast.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
medium_username                           : aheze
github_username                           : aheze
reddit_username                           : aheze



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : It's like Command+F, but for your camera.
    description                           : Ctrl+F if you prefer Windows.
    fontawesome_icon_name                 : search
    
  - title                                 : Works with anything
    description                           : Books, textbooks, worksheets... literally anything.
    fontawesome_icon_name                 : magic

  - title                                 : Fast, accurate, free
    description                           : Find is faster than the human eye.
    fontawesome_icon_name                 : star

  - title                                 : Photos
    description                           : Blast through hundreds of photos in minutes.
    fontawesome_icon_name                 : images

  - title                                 : Caching
    description                           : Cache your photos for super-fast, super-accurate results.
    fontawesome_icon_name                 : save
  
  - title                                 : Lists
    description                           : Group words together. Boost your efficiency.
    fontawesome_icon_name                 : list

  - title                                 : Combine lists
    description                           : Look for multiple words at the same time. Great for vocab assignments.
    fontawesome_icon_name                 : layer-group

  - title                                 : Let Find read the nutrition label for you
    description                           : Gluten-free? Have allergies? Gather them into a list, and Find will keep an eye out!
    fontawesome_icon_name                 : cookie-bite
    
  - title                                 : Haptics
    description                           : Receive a light tap when Find detects results.
    fontawesome_icon_name                 : play

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#0096cc"
topbar_transparency                       : 0.0
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerImage.jpg                   # Replace with alternative image path or image URL.
cover_overlay_color                       : "#004b66"
cover_overlay_transparency                : 0.5

device_color                              : blue                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#0096cc"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#0096cc"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
