
# App Info
ios_app_id                                : 1506500202                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

include: [".well-known"]

appstore_link                             : https://apps.apple.com/app/id1506500202                                          # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appIcon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : "Find: Make Photos Searchable"                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : An app to find text in real life.
app_description                           : Look for text in screenshots, books, and even nutrition labels. Search your entire photo library, or use the camera and speed through forms and worksheets in seconds.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
medium_username                           : aheze
github_username                           : aheze
reddit_username                           : aheze

background_404                            : assets/mountains.jpg


# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Photos
    description                           : Search hundreds of photos in seconds.
    fontawesome_icon_name                 : search

  - title                                 : Camera
    description                           : It's like Live Text but on steroids.
    fontawesome_icon_name                 : camera

  - title                                 : Lists
    description                           : Search for multiple words at the same time.
    fontawesome_icon_name                 : list

  - title                                 : Search Bar
    description                           : Comes with advanced options.
    fontawesome_icon_name                 : cog

  - title                                 : Works anywhere there is text
    description                           : Books, forms, worksheets, nutrition labels...
    fontawesome_icon_name                 : magic

  - title                                 : Privacy built-in
    description                           : 100% offline with no analytics or data collection.
    fontawesome_icon_name                 : hand-paper

  - title                                 : Fast, accurate, free
    description                           : No ads, in-app purchases, subscriptions, etc.
    fontawesome_icon_name                 : dollar-sign

  - title                                 : It's actually so fast
    description                           : Launches in a split second and produces results instantly.
    fontawesome_icon_name                 : rocket
    
  - title                                 : Accessibility
    description                           : Full VoiceOver support with extended accessibility features.
    fontawesome_icon_name                 : universal-access

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.

 

# Theme Settings
topbar_color                              : "#0096cc"
topbar_transparency                       : 0.0
topbar_title_color                        : "#ffffff"

cover_image                               : assets/HeaderImage.jpg                   # Replace with alternative image path or image URL.
cover_overlay_color                       : "#004b66"
cover_overlay_transparency                : 0.5

device_color                              : blue                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#004F80"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#007eef"
feature_icons_background_color            : "#F2F2F2"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
